spring:
  application:
    name: cards-service
  
  config:
    # import: "optional:configserver:http://localhost:8888"
    import: "optional:configserver:http://config-server:8888"

  reactor:
    context-propagation: auto

logging:
  file:
    name: logs/miapp.log
  level:
    root: INFO